id: PE9A6906E
initial_creation_type: input
source_metadata:
  title: Ngawang Tendar Series
  language: en
  description: 'Texts by and about the renowned Mongolian scholar Ngawang Tendar (ngag
    dbang bstan dar, 1759/1751–1831):'
  volume:
    a1e7e68d8fee40f29281c71a4423707e:
      title: On Literary Composition
      parent: Literary Theory
created_at: '2022-03-01T01:00:08.884912'
last_modified_at: '2022-03-01T01:00:08.884918'
